# Numpy

###### NumPy is a powerful Python library that stands for "Numerical Python." It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. NumPy is widely used in scientific computing, data analysis, and machine learning applications.

In [1]:
import numpy as np

#### Creating a NumPy array from a Python list:

In [2]:
arr = np.array([1, 2, 3, 4, 5,6])
arr

array([1, 2, 3, 4, 5, 6])

#### Creating a 2D NumPy array:

In [3]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

#### Accessing the shape of a NumPy array:

In [4]:
shape = arr_2d.shape
shape

(2, 3)

#### Accessing the dimensions of a NumPy array:

In [5]:
dimensions = arr_2d.ndim
dimensions

2

#### Accessing the number of elements in a NumPy array:

In [6]:
num_elements = arr_2d.size
num_elements

6

#### Reshaping a NumPy array:

In [7]:
reshaped_arr = arr.reshape((2, 3))
reshaped_arr

array([[1, 2, 3],
       [4, 5, 6]])

#### Accessing specific elements in a NumPy array:

In [8]:
element = arr[0]  # Access first element
element

1

#### Slicing a NumPy array:

In [9]:
slic = arr[1:4]  # Access elements from index 1 to 3
slic

array([2, 3, 4])

#### Finding the maximum element in a NumPy array:

In [10]:
max_value = arr.max()
max_value

6

#### Finding the minimum element in a NumPy array:

In [11]:
min_value = arr.min()
min_value

1

#### Finding the sum of all elements in a NumPy array:

In [13]:
sum_value = arr.sum()
sum_value

21

#### Finding the mean of elements in a NumPy array:

In [14]:
mean_value = arr.mean()
mean_value

3.5

#### Finding the standard deviation of elements in a NumPy array:

In [15]:
std_dev = arr.std()
std_dev

1.707825127659933

#### Transposing a NumPy array:

In [16]:
transposed_arr = arr_2d.T
transposed_arr

array([[1, 4],
       [2, 5],
       [3, 6]])

#### Performing element-wise addition of two NumPy arrays:

In [18]:
arr_1 = np.array([1,2,3,4,5])
arr_2 = np.array([6,7,8,9,10])

sum_arr = arr_1 + arr_2
sum_arr

array([ 7,  9, 11, 13, 15])

#### Performing element-wise multiplication of two NumPy arrays:

In [19]:
mult_arr = arr_1 * arr_2
mult_arr

array([ 6, 14, 24, 36, 50])

#### Performing matrix multiplication using NumPy arrays:

In [20]:
mat_mult = np.matmul(arr_1, arr_2)
mat_mult

130

#### Finding the index of the maximum element in a NumPy array:

In [21]:
max_index = arr.argmax()
max_index

5

#### Finding the index of the minimum element in a NumPy array:

In [22]:
min_index = arr.argmin()
min_index

0

#### Creating an array of evenly spaced values within a range:

In [24]:
start = 1
stop = 10
step = 2

range_arr = np.arange(start, stop, step)
range_arr

array([1, 3, 5, 7, 9])

#### Creating an array of evenly spaced values within a specified interval: 

In [26]:
num = 2

linspace_arr = np.linspace(start, stop, num)
linspace_arr

array([ 1., 10.])